apiVersion: v1
kind: Pod
metadata:
  name: sevgingalibov-sample-java
  annotations:
    instrumentation.opentelemetry.io/inject-java: "true"	# This annotation must be added.
spec:
  containers:
  - name: sevgingalibov-sample-java
    image: ghcr.io/open-telemetry/opentelemetry-operator/e2e-test-app-java:main
    ports:
      - containerPort: 8080
        protocol: TCP

