apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-namespace-intrumentation-injector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: auto-namespace-intrumentation-injector
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["opentelemetry.io"]
    resources: ["instrumentations"]
    verbs: ["create", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auto-namespace-intrumentation-injector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: auto-namespace-intrumentation-injector
subjects:
  - kind: ServiceAccount
    name: auto-namespace-intrumentation-injector
    namespace: {{ .Release.Namespace }}
